# Generated by Django 3.2 on 2021-09-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=3, null=True)),
                ('file_string', models.TextField(null=True)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('anchor', models.IntegerField()),
                ('linker', models.IntegerField()),
                ('file_type', models.CharField(max_length=3, null=True)),
                ('file_string', models.TextField(null=True)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FragmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Growing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_points', models.TextField(null=True)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.complex')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.core')),
                ('fragment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.fragmentset')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=3)),
                ('file_string', models.TextField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.complex')),
            ],
        ),
        migrations.CreateModel(
            name='SearchPointData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.complex')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.ligand')),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('file_type', models.CharField(max_length=3)),
                ('file_string', models.TextField()),
                ('growing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.growing')),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.ligand'),
        ),
    ]
