# Generated by Django 3.2 on 2021-07-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=3)),
                ('file_string', models.TextField()),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('accessed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=3)),
                ('file_string', models.TextField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.complex')),
            ],
        ),
        migrations.CreateModel(
            name='SearchPointData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.complex')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_grow.ligand')),
            ],
        ),
    ]
