# Generated by Django 3.1.2 on 2022-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_grow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentset',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
